server:
  port: 8000

spring:
  application:
    name: microservice-provider-user #微服务的名称，用于注册到Eureka Server上的应用名称
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                         # 指定数据源
    platform: h2                      # 指定数据源类型
    schema: classpath:schema.sql      # 指定h2数据库的建表脚本
    data: classpath:data.sql          # 指定h2数据库的数据脚本

# 配置日志级别，让hibernate打印出执行的SQL
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

## 公开的INFO，有些信息获取不到，待查明原因
info:
  app:
    name: ${project.artifactId}
    encoding: ${project.build.sourceEncoding}
    java:
      source: ${java.version}
      target: ${java.version}

eureka:
  client:
    healthcheck:
      enabled: true #客户端向Eurek Server传播健康状态，需要引入Spring Boot Actuator
    service-url:
      defaultZone: http://localhost:8761/eureka/ #Eureka Server的交互地址，注册和发现都需要用它-单点
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/ #Eureka Server的交互地址，注册和发现都需要用它-集群
      #defaultZone: http://user:password123@localhost:8761/eureka/ #Eureka Server-需要认证-单点
  instance:
    prefer-ip-address: true #将自己的IP注册到Eureka Server
    metadata-map:
      my-metadata: 我自定义的元数据       # 自定义的元数据，key/value都可以随便写。
    lease-renewal-interval-in-seconds: 5 #心跳检测间隔时间，默认30秒，开发时配置，生产环境不动
    lease-expiration-duration-in-seconds: 10 #检测异常移除服务时间，默认90秒，开发时配置，生产环境不动