spring:
  application:
    name: microservice-discovery-eureka-server-ha

---
spring:
  profiles: peer1 # 指定profile=peer1

server:
  port: 8761
eureka:
  instance:
    hostname: peer1 # 指定当profile=peer1时，主机名是peer1
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/ #将自己注册到peer2这个Eureka Server中

---
spring:
  profiles: peer2 # 指定profile=peer2

server:
  port: 8762
eureka:
  instance:
    hostname: peer2 # 指定当profile=peer2时，主机名是peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/ #将自己注册到peer1这个Eureka Server中

